# Generated by Django 3.2 on 2021-05-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
