# Generated by Django 3.2 on 2021-05-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_view_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
